apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u1arnuky9-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:5fc743085b65afcb5ad13eb869b7b28da08df790@sha256:1a86e2dbacc42aaf59ff1d2563744cdde1456a04dbc6a814583f592ce01d35f2
          name: container-image
